# Generated by Django 4.0.4 on 2022-05-31 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasFeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-active', 'name']},
        ),
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=42, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BlockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.member')),
            ],
        ),
    ]
