# Generated by Django 4.0.4 on 2022-05-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_blockdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasfeedata',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='transactiondata',
            options={'ordering': ['date']},
        ),
    ]
