# Generated by Django 4.0.4 on 2022-06-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_gasfeedata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockdata',
            options={'ordering': ['date', 'member']},
        ),
    ]
